# -*- coding: utf-8 -*-
"""coba.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uKyzJJcBoTpWB5AA_3dHWLb-BcKbi4lw
"""

import streamlit as st
import joblib
import numpy as np

# Load the machine learning model
model = joblib.load('iris_model.pkl')

def main():
    st.title("Machine Learning Model Deployment 🌿")

    # Add user input components for 4 features
    sepal_length = st.slider('Sepal Length', min_value=0.0, max_value=10.0, step=0.1)
    sepal_width = st.slider('Sepal Width', min_value=0.0, max_value=10.0, step=0.1)
    petal_length = st.slider('Petal Length', min_value=0.0, max_value=10.0, step=0.1)
    petal_width = st.slider('Petal Width', min_value=0.0, max_value=10.0, step=0.1)

    if st.button('Make Prediction'):
        features = [sepal_length, sepal_width, petal_length, petal_width]
        result = make_prediction(features)
        st.success(f'The prediction is: {result}')

def make_prediction(features):
    """Use the loaded model to make predictions"""
    input_array = np.array(features).reshape(1, -1)
    prediction = model.predict(input_array)
    return prediction[0]

if __name__ == "__main__":
    main()